### ISSUE TITLE
Homebrew install/update

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/xcode-kotlin#47]
The install process is not great. Explore homebrew install.

How to make one is not super clear. Here's a place to start: https://docs.brew.sh/Formula-Cookbook

**Comment by TadeasKriz** [comment]
I've setup a `homebrew-touchlab` tap repository in the `touchlab` org. In there is a single formula for xcode-kotlin.

You can install it using: 
```
brew install --head touchlab/homebrew-touchlab/xcode-kotlin
```

However the way I did it is kinda hacky, because it seems homebrew shouldn't be used this way. It should leave some artefacts behind, where I just ran `setup.sh` and then created an empty `SUCCESS` file so that homebrew thinks everything is alright. I've also set it to `keg-only` mode where it shouldn't pollute the `PATH` (with the `SUCCESS` file).

@kpgalligan Take a look and let me know if this is what you imagined, or you'd like something else. I tried to make it as simple as possible for now and we can improve on that.
