### ISSUE TITLE
Try multiple Xcode installs and see if ~/Library/Developer/Xcode is the only folder

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/xcode-kotlin#49]
Xcode 11 required installing scripts where Xcode was installed. Before and after 11, the files can be installed at `~/Library/Developer/Xcode`. I don't know if there is more than one of those folders if there are multiple versions of Xcode installed. If somebody has multiple versions of Xcode (I usually do, but apparently not today), see if there are multiple directories under `~/Library/Developer/`.

**Comment by TadeasKriz** [comment]
One directory, but I don't see that being different with Xcode 11. To be honest I'm a bit lost about the differences with Xcode 11, compared to Xcode 13.3. It seems the difference was in how the language specification was installed for Xcode 11. The script installs it directly into the Xcode.app, instead of putting it in the `~/Library/Developer/Xcode/Specifications`. What I don't understand is, that we no longer use the metadata plist file for kotlin (`Xcode.SourceCodeLanguage.Kotlin.plist`). I'll probably look more into this to figure it out.

@kpgalligan How old Xcodes do we want to support? Xcode 11.x and even Xcode 12.x are no longer supported on Monterey, so I would have to figure out a way to get older macOS running somewhere if we need those.

**Comment by kpgalligan** [comment]
We chatted about versions, but as a reminder, the latest major version, and for a while, the previous when the major changes. 11 was the only really weird one, though. OK, closing...
